import { useState } from 'react';

const examples = ["Let's circle back on this tomorrow.", "Do we have the bandwidth for this?", "Let's circle back tomorrow, touch base with design, and focus on the low-hanging fruit."];
export default function App() {
  const [text, setText] = useState(examples[0]); const [result, setResult] = useState(); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function translate(event) {
    event.preventDefault(); if (!text.trim()) return; setLoading(true); setError('');
    try { const response = await fetch('/api/v1/translations', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({text}) }); if (!response.ok) throw new Error('Translation request failed.'); setResult(await response.json()); }
    catch (e) { setError(e.message + ' Is the backend running on port 8080?'); } finally { setLoading(false); }
  }
  return <main><section className="hero"><p className="eyebrow">WORKPLACE LANGUAGE, CLARIFIED</p><h1>Corporate jargon translator</h1><p>Paste a phrase, message, or email to identify and explain its workplace jargon.</p></section><section className="panel"><form onSubmit={translate}><label htmlFor="input">What did they say?</label><textarea id="input" value={text} onChange={e => setText(e.target.value)} maxLength="5000" placeholder="Paste a phrase, message, or email excerpt…"/><div className="actions"><button disabled={loading}>{loading ? 'Translating…' : 'Translate'}</button><span>{text.length}/5000</span></div></form><div className="examples">Try: {examples.map(example => <button key={example} onClick={() => setText(example)}>{example}</button>)}</div>{error && <p className="error">{error}</p>}</section>{result && <section className="result"><div className="meta"><span>{result.inputType.toLowerCase()}</span>{result.cached && <span>cached</span>}</div><article><h2>Plain meaning</h2><p>{result.plainMeaning}</p></article><article><h2>Professional explanation</h2><p>{result.professionalExplanation}</p></article><article className="reply"><h2>Suggested reply</h2><p>{result.suggestedReply}</p></article>{result.jargonTranslations?.length > 1 && <div className="translations"><h2>Detected jargon</h2>{result.jargonTranslations.map(item => <article className="translation" key={item.term}><h3>{item.term}</h3><p><strong>Meaning:</strong> {item.plainMeaning}</p><p><strong>Reply:</strong> {item.suggestedReply}</p>{item.dictionaryResults.length > 0 && <small>Source: {item.dictionaryResults.map(d => d.provider).join(', ')}</small>}</article>)}</div>}{result.dictionaryResults.length > 0 && <small>Dictionary source: {result.dictionaryResults.map(d => d.provider).join(', ')}</small>}</section>}</main>;
}